project:
  type: website

website:
  title: "Brunei R User Group"
  navbar:
    pinned: true
    logo: img/bruneiR-profile.png
    left:
      - text: "Admin"
        href: admin.qmd
      - text: "Events"
        href: events.qmd
      - text: "Blog"
        href: blog.qmd
        
    right:
      - icon: github
        href: https://github.com/
      - icon: instagram
        href: https://instagram.com/brunei.r.user
      - icon: envelope
        aria-label: email
        href: "mailto:bruneirofficial@gmail.com"
  search: 
    location: navbar
    type: textbox
    
format:
  html:
    fontsize: 1.1em
    theme: 
      - flatly
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true

editor: visual




